
development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  user: jesse 
  password: '123456'
  host: localhost




# test:
#   adapter: postgresql
#   database: my_database_test
#   pool: 5
#   timeout: 5000

# production:
#   adapter: postgresql
#   database: my_database_production
#   pool: 5
#   timeout: 5000